name: 'tag_name'
on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: 'ls -la'
      
      - name: Checkout ioc repo
        uses: actions/checkout@master
        with:
          repository: ArturGrigoryan1/lesson_09_06_terraform_action
          path: terraform
          
      - run: 'ls -la'
      
      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Terraform apply
        env:
          NAME: "PROD_+${{  github.ref_name }}"
        run: |
          ls -la
          cd terraform/
          ls -la
          terraform init -upgrade
          terraform apply -auto-approve -var="instance_name=${{ env.NAME }}" -var="file_data="../user_data.sh""
          
          

      
